### ISSUE TITLE
Bullets through lightsaber

### ISSUE THREAD

**Issue by JoshuaAtherton** [RedLeader179/Zerlin#14]
Some bullets occasionally go through Zerlin's light saber.

**Comment by steveng9** [comment]
Did this happen when you were moving the lightsaber towards the laser? Or did it happen otherwise? (just for me to track down the problem)

**Comment by JoshuaAtherton** [comment]
It was mostly happening when when the lightsaber was not moving.

**Comment by steveng9** [comment]
No way! you'll have to show me tonight?

**Comment by JoshuaAtherton** [comment]
I might have seen something bounce off the back so. We can delete this or talk about it tomorrow
